# 06. Matrix operations
Hardware 1, Python Labs for Mathematics and Physics<br>
2022-2026<br>
Information and Communication Technology<br>
[Metropolia University of Applied Sciences](https://www.metropolia.fi/en)

## Background and aim

See Timo Salin's Mathematics Lecture Notes, Ch 8. Matrices.

The aim of these exercises is to learn to solve matrix problems with Python's numpy library.

## Setup

We use `numpy` and `matplotlib` libraries. 

In addition, we need 
- linear algebra functions from `numpy.linalg` sublibrary
- numpy's trigonometric functions, and
- numpy's matrix dot production function

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import dot
from numpy.linalg import det, inv, solve

## 1. Matrix operations with numpy arrays

Let's create two dimensional numpy arrays. We need to give a nested list as an input for `numpy.array`. See: [numpy.array, Examples](https://numpy.org/doc/stable/reference/generated/numpy.array.html).

In [2]:
# A and B are two dimensional arrays. Notice the double [] and commas
A = np.array([[1, 0], [-1, 4]]) 
B = np.array([[0, 5], [7, 1]])

print('A =\n', A)
print('B =\n', B)

print('A.shape =', A.shape)
print('B.shape =', B.shape)

A =
 [[ 1  0]
 [-1  4]]
B =
 [[0 5]
 [7 1]]
A.shape = (2, 2)
B.shape = (2, 2)


### 1.1. Matrix addition

Matrix addition can be calculated by adding the matrices together.

In [3]:
C = A + B
print('C =\n', C)

C =
 [[1 5]
 [6 5]]


### 1.2. Matrix subtraction

Similarly as matrix addition, subtraction can be calculate by subtracting the matrices.

In [4]:
D = A - B
print('D =\n', D)

D =
 [[ 1 -5]
 [-8  3]]


### 1.3. Scalar multiplication

Arrays can be directly multiplied by a scalar.

In [5]:
E = 2*A
print('E =\n', E)

E =
 [[ 2  0]
 [-2  8]]


### 1.4. Matrix (dot) product

For matrix product we use dot product. The inner dimensions of the arrays needs to be same.

**NOTE:** Introduced in NumPy 1.10.0, the @ operator is preferable to other methods when computing the matrix product between 2d arrays. The numpy.matmul function implements the @ operator. 

In [6]:
A = np.array([[1, 0], [-1, 4], [2, 5]])
B = np.array([[1, 4], [0, 2]])

print('A = \n', A)
print('B = \n', B)
print('A.shape =', A.shape)
print('B.shape =', B.shape)

A = 
 [[ 1  0]
 [-1  4]
 [ 2  5]]
B = 
 [[1 4]
 [0 2]]
A.shape = (3, 2)
B.shape = (2, 2)


In [7]:
C = np.dot(A, B)
print('C = AB = \n', C)

C = AB = 
 [[ 1  4]
 [-1  4]
 [ 2 18]]


In [8]:
# Preferred way to calculate dot-product between 2d matrices
C2 = A @ B
print('C2 = \n', C2)

C2 = 
 [[ 1  4]
 [-1  4]
 [ 2 18]]


In [9]:
# The shape of the resulting matrix (rows, columns)
print('C.shape =', C.shape)

C.shape = (3, 2)


A second example. The first array has shape 2x3 and the second array 3x1.

In [10]:
D = np.array([[1, 2, 3], [4, 5, 6]])
E = np.array([[1], [2], [4]])
F = D @ E

print('D = \n', D)
print('E = \n', E)
print('F = DE = \n', F)
print('D.shape =', D.shape)
print('E.shape =', E.shape)
print('F.shape =', F.shape)

D = 
 [[1 2 3]
 [4 5 6]]
E = 
 [[1]
 [2]
 [4]]
F = DE = 
 [[17]
 [38]]
D.shape = (2, 3)
E.shape = (3, 1)
F.shape = (2, 1)


### 1.5. Practice

Find $A \cdot B$, when $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ -1 & 0 \end{pmatrix}$
and $B = \begin{pmatrix} -1 \\ 2 \\ -1 \end{pmatrix}$.

Find $C \cdot D$, when $C = \begin{pmatrix} 1 & 1 & 1 \\ 2 & 1 & 0 \\ 3 & -1 & 2 \end{pmatrix}$
and $D = \begin{pmatrix} 0 & 3 & 1 \\ 4 & -1 & 0 \\ 2 & 2 & 1 \end{pmatrix}$.

## 2. Linear algebra

`numpy.linalg` sublibrary has functions to:
- compute the inverse of a matrix [`numpy.linlag.inv`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html#numpy.linalg.inv)
- compute the determintant of an array [`numpy.linalg.det`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html#numpy.linalg.det)
- solve a linear matrix equation, or system of linear scalar equation [`numpy.linalg.solve`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html#numpy.linalg.solve)

### 2.1. Computing the inverse of matrix

In [11]:
A = np.array([[1., 2.], [3., 4.]])
Ainv = np.linalg.inv(A)

print('A = \n', A)
print('Ainv = \n', Ainv)

A = 
 [[1. 2.]
 [3. 4.]]
Ainv = 
 [[-2.   1. ]
 [ 1.5 -0.5]]


### 2.2 Computing the determinant of an array

In [12]:
A = np.array([[1, 2], [3, 4]])
detA = np.linalg.det(A)

print('A = \n', A)
print('det(A) =', detA)

A = 
 [[1 2]
 [3 4]]
det(A) = -2.0000000000000004


### 2.3. Solving a system of equations

Solve the system of equations

\begin{align*} 
x_0 + 2x_1 &=  1 \\ 
3x_0 + 5x_1 &=  2
\end{align*}


In [13]:
A = np.array([[1, 2], 
              [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(A, b)

print('A = \n', A)
print('b =', b)
print('x =', x)

A = 
 [[1 2]
 [3 5]]
b = [1 2]
x = [-1.  1.]


---
## About floating point numbers

In programming languages real numbers are presented as floating point numbers. For exampe, $1234000$ can be presented $1.234\times 10^6$, or written shortly $1.234e6$.

See: [Floating-point arithmetic, Wikipedia](https://en.wikipedia.org/wiki/Floating-point_arithmetic)

Example, if you got results like

In [14]:
detA = -8.612335e-15
print(detA)

-8.612335e-15


This is actually very close to zero

In [15]:
# Let's use format string f"{variable:format}"
print(f'{detA:.32f}')

-0.00000000000000861233499999999995


If we round the value to 8 decimals, we can see it more clearly

In [16]:
print(np.round(detA, 8))

-0.0


Read more: [f-strings a new and improved way to format strings in python](https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python)

### What is the smallest number that differs from 1.0?

Sometimes you might get very small or very large values as a result. Always remember check the mantissa (e-part) to get an idea of the scale of the value. 

However, there is a limit for how small differences between real values we can present with floating point numbers. The smallest defference between 1.0 and the next smallest represtanble float number larger than 1.0 is usually marked with variable `eps`. For example, for 64-bit binary floats in the IEEE-754 standard, eps = 2**-52, approximately 2.22e-16.

Source: [Attribute: eps, numpy.finfo](https://numpy.org/doc/stable/reference/generated/numpy.finfo.html)

In [17]:
# Print out the value for eps
eps = np.finfo(float).eps
print(eps)
print(2**(-52))

2.220446049250313e-16
2.220446049250313e-16


In [18]:
# Show all decimals without mantissa (e-part)
print(f"{np.finfo(float).eps:.32f}")

0.00000000000000022204460492503131


Now, let's check if Is 1.0000000000000001 greater than 1.0

In [19]:
# 1.0 plus a very small number
x1 = 1.0 + 1.0e-16

print(x1)
print(x1 > 1.0)

1.0
False


How about, is 1.0000000000000002 greater than 1.0?

In [20]:
# 1.0 plus a little bigger number
x2 = 1.0 + 2.0e-16

print(x2)
print(x2 > 1.0)

1.0000000000000002
True


Lastly we compare 1.0000000000000002 to 1.0000000000000001

In [21]:
print(x2 > x1)

True


To conclude, the numerical accuracy of the floating point arithmetics is about 16 decimals (52 bits).

### What are the largest and smallest floating point numbers?

Then, how big and small numbers we can present with floating point numbers. Let's change the mantissa (e-part) to find it out.

Notice, that floating point presentation has a special code for infinity or not-a-number (nan).

In [22]:
# 10^400?
1.0e400

inf

In [23]:
# 10^308?
1.0e308

1e+308

In [24]:
# 10^(-323)?
1.0e-323

1e-323

In [25]:
# 10^(-400)?
1.0e-400

0.0

### Not-a-number and infinity

Not-a-number has a special symbol in floating point presentation

In [26]:
x = np.nan
print(x)

nan


We can make calculations with `nan` or `inf`, but the result remains the same

In [27]:
x + 3, 3*x, x/x

(nan, nan, nan)

In [28]:
y = np.inf
y + 3, y/x, -y

(inf, nan, -inf)