# Lab 6. Matrices
Hardware 1 - Mathematics Python Labs<br>
Information and Communication Technology<br>
Metropolia University of Applied Sciences

## Setup

Remember add your `name`, `student_id`, and `date_returned`.

Read necessary libraries and functions.

In [17]:
name = "Daniel Larva"
student_id = 2511908 # Write your student number here
date_returned = "14/2/2026"

In [18]:
import numpy as np
import matplotlib.pyplot as plt

---
## Problem 1

In this problem the aim is to practise matrix multiplication (dot product). The matrices A and B generated by the code. Your task is:

1. Calculate the matrix dot product $C = AB$ and print it out. 
2. Calculate the matrix dot product  $D = BA$ and print it out.
3. Compare C and D. What do you observe?

Tips
- Study `numpy.isclose()` and `numpy.allclose()` and use them for comparison
- Use `numpy.round()` to round the results of dot product to few decimals. 


In [19]:
# Initialize random number generator
rng = np.random.default_rng(student_id)

# Generate two random matrices
A = rng.integers(low=0, high=10, size=(5, 5))
B = np.linalg.inv(A)

# Print them
print('A = \n', A)
print('B = \n', B)

A = 
 [[8 7 7 8 3]
 [1 6 7 2 6]
 [1 6 3 1 4]
 [5 9 6 5 9]
 [0 8 7 5 7]]
B = 
 [[ 5.40641312e-02  7.75540641e-02 -3.72856078e-04  9.80611484e-02
  -2.15510813e-01]
 [ 4.32513050e-02 -1.37956749e-01  3.99701715e-01 -1.21551081e-01
   2.75913497e-02]
 [ 5.63012677e-02  2.94556301e-01 -8.31469053e-02 -1.32363908e-01
  -5.89112603e-02]
 [ 3.20656227e-02 -2.22967934e-01 -1.86428039e-01  3.05741984e-02
   2.44593587e-01]
 [-1.28635347e-01  2.23713647e-02 -2.40492170e-01  2.49440716e-01
  -4.47427293e-03]]


In [20]:
# My code to solve C = AB
C = np.dot(A, B)
print('C = AB = \n', C)

C = AB = 
 [[ 1.00000000e+00  6.93889390e-17  1.11022302e-16  0.00000000e+00
  -1.12757026e-17]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00  0.00000000e+00
  -7.80625564e-17]
 [-1.11022302e-16  5.55111512e-17  1.00000000e+00  0.00000000e+00
   3.12250226e-17]
 [-2.77555756e-17  4.16333634e-17 -3.33066907e-16  1.00000000e+00
  -1.17093835e-16]
 [ 2.77555756e-17 -4.16333634e-17  1.11022302e-16  0.00000000e+00
   1.00000000e+00]]


In [21]:
# My code to solve D = BA
D = np.dot(B, A)
print('D = BA = \n', D)


D = BA = 
 [[ 1.00000000e+00  2.22044605e-16  2.49800181e-16 -1.38777878e-16
   2.77555756e-17]
 [-4.16333634e-16  1.00000000e+00 -2.74086309e-16 -2.94902991e-16
  -1.90819582e-16]
 [ 1.66533454e-16  1.11022302e-16  1.00000000e+00  7.63278329e-17
   6.24500451e-17]
 [ 1.07552856e-16  4.44089210e-16 -2.77555756e-17  1.00000000e+00
  -2.77555756e-17]
 [ 2.22044605e-16  3.40005801e-16  4.77048956e-17  1.29236899e-16
   1.00000000e+00]]


In [32]:
# Compare C and D 
allc = np.allclose(C, D)
print(f'Are the matrices equal element-wise? {allc}')
isc = np.isclose(C, D)
print(f'Matrices C and D are about equal in the following positions:\n {isc}')

Are the matrices equal element-wise? True
Matrices C and D are about equal in the following positions:
 [[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


---
## Problem 2

in this problem the aim is first to use numpy's function to solve equations and then write own algorithm to do the same thing. Again, the arrays A and b are generated for you. You need not to write them yourself.

First, use `numpy.linalg.solve()` to solve these equations:

\begin{align*} 
A_{11} x + A_{12} y + A_{13} z &=  b_1 \\ 
A_{21} x + A_{22} y + A_{23} z &= b_2 \\
A_{31} x + A_{32} y + A_{33} z &= b_3
\end{align*}

Then, write your own code to solve them. In your own code:
- Do NOT use numpy function NOR any other ready-made functions, but
- Write your own algorithm to solve the equations

Finally, compare the solutions and verify they give same results. Use `numpy.isclose()` function for that. 

In [23]:
# Initialize random number generator
rng = np.random.default_rng(student_id)

# Generate two random matrices
A = rng.integers(low=-10, high=10, size=(3, 3))
b = rng.integers(low=-10, high=10, size=(3, 1))

# Print them
print('A = \n', A)
print('b = \n', b)

A = 
 [[ 6  5  4]
 [ 6 -4 -8]
 [ 2  5 -6]]
b = 
 [[ 2]
 [-8]
 [ 2]]


In [24]:
# Using numpy.linalg.solve to solve Ax = b

In [25]:
# My code to solve the linear equations for x, y and z

In [26]:
# Compare the results and verify they give same results

---
## Problem 3
Solve the following equations using numpy linear algebra operations

$$ Ax = b $$

Notice, that A and b are already defined, you don't need to rewrite them.

Give the values for x with three decimals.

In [27]:
# Initialize random number generator
rng = np.random.default_rng(student_id)

# Generate two random matrices
A = np.round(rng.uniform(-1000, 1000, size=(7, 7)), 4)
b = A @ np.arange(1, 8).reshape((7, 1))

# Print them
print('A = \n', A)
print('b = \n', b)

A = 
 [[ 562.411   646.1174 -762.9356  557.4824  266.7975  261.0382 -664.9743]
 [ 176.9459  247.6863  933.5873  742.2966  152.3078  812.2386   67.5646]
 [ 307.6482  650.7929  140.9363 -566.0341  246.4022 -693.0793 -445.084 ]
 [-803.4632 -862.3311 -693.7868  119.8004 -653.0624 -576.7569  711.924 ]
 [-478.7514  262.6484  558.6774  861.705   628.0826  223.7481  -11.9888]
 [-558.8173  -68.6542 -264.768   126.3287 -951.9923  686.1199  244.6001]
 [ 785.0618 -571.9429  225.5638 -403.6251 -520.9776   11.2869   48.8267]]
b = 
 [[   41.1652]
 [12550.1896]
 [-6274.1463]
 [-5872.6696]
 [ 9568.3776]
 [   83.8437]
 [-3492.0127]]


In [28]:
# My solution for problem 3


---
## Problem 4

Consider a $9 \times 9$ matrix $A$, where each element is defined by the following formula

$A_{nm} = (-1)^{(n+m)} \cdot (n + 2m)$

where both indices n and m range from 1 to 9 (inclusive).

Your task is:

- Step 1. Matrix construction 
   - Write a Python program using numpy to construct this matrix. Do not manually type each element!
- Step 2. Determinant calculation
   - Calculate the determinant of matrix A using numpy's build-in functions.
- Step 3. Analysis
   - What is the determinant value?
   - What does that tell you about the matrix?

Tips
- Here you **can use for-loops** for indexing both rows and columns of the array
- Notice, that indexing in numpy arrays starts from 0, but for the formula it starts from 1. You should take care of this in your code.
- It is a good practise first to initialize the array. You can do that for example using the function `numpy.zeros()`.

In [29]:
# My solution for problem 4

---
## Problem 5


If $ A(a, x) = \left( \begin{matrix}
a + x & a - x & a - x \\
a - x & a + x & a - x \\
a - x & a - x & a + x
\end{matrix} \right)$, find $x > 0$, so that $det(A(a, x)) = 0$. 

How are $a$ and $x$ related?

This last problem can be solved combining matrix operations and graphics.

Tips
- First, create a function that returns a numerical matrix for input variables a and x
- Create a second function that calls the first function and calculates and returns the determinant value of the matrix. 
- Create linearly spaced values for $x \in [0, 10]$, for example. Use `numpy.linspace`.
- Calculate the output of the second function (e.g. $f(x,a) = det(A(x, a))$) and store the values to another variable, for example y. 
- Draw a graph of the determinant versus value of x, e.g. plot(x, y) 
- Finally, from the graph, find the value of x, when $y = 0$.
- **NOTE** $x = 0$ is NOT the answer we are looking for! 

The value for $a$ is given below for you.

In [30]:
# Initialize random number generator
rng = np.random.default_rng(student_id)

# Generate random value for a
a = np.round(rng.uniform(1.0, 3.0), 1)
print(f'a = {a}')

a = 2.6


In [31]:
# Solution for problem 5


